### ISSUE TITLE
ord wallet mint --rune will have different errors depends on if the wallet is funded or not

### ISSUE THREAD

**Issue by testpower4** [ordinals/ord#3634]
ord --version
ord 0.18.1

#unfunded new wallet
ord --config /opt/disk/ord/runes.yaml wallet --server-url="http://127.0.0.1:80" --name rand  mint --fee-rate 188 --rune UNCOMMON.GOODS
error: JSON-RPC error: RPC error response: RpcError { code: -4, message: "Insufficient funds", data: None }

# funded wallet
ord --config /opt/disk/ord/runes.yaml wallet --server-url="http://127.0.0.1:80" --name funded_wallet_1  mint --fee-rate 188 --rune UNCOMMON.GOODS
error: output in wallet but not in ord server: 35863ef52429ead74edb0824e30cbcac7f1e8bc4a7e5ce210f07ab9db7a521cc:1

**Comment by raphjaph** [comment]
try updating to the latest release. We fixed some of those issues

**Comment by himanshu64** [comment]
still the same issue with 0.18.5 version , @raphjaph any update on this
