### ISSUE TITLE
ordinals.com is now drawing a scrollbar next to each inscription

### ISSUE THREAD

**Issue by gmart7t2** [ordinals/ord#3990]
![Screenshot_2024-10-09_04-03-33](https://github.com/user-attachments/assets/40fbd85e-46c6-4c10-a75d-cb4788bbcf59)

**Comment by gmart7t2** [comment]
On Android, too:
![Screenshot_20241009_040555_Presearch](https://github.com/user-attachments/assets/a29d18ec-78cb-49a7-9300-a293ec4c92b9)

**Comment by gmart7t2** [comment]
It looks like this was introduced by #3947 removing the `scrolling=no`.

**Comment by gmart7t2** [comment]
Size by side comparison of 0.20.0 and 0.20.1:
![Screenshot_2024-10-09_04-23-28](https://github.com/user-attachments/assets/1ad4827b-640c-466b-bf62-bf3c82a695ef)

**Comment by casey** [comment]
I landed a partial fix for this in #4042. The image preview is now fixed, so that the images don't overflow. This should remove all scrollbars on image inscriptions. I also removed scrollbars entirely from inscription thumbnails. This means that the only scrollbars remaining are on non-image inscriptions on /inscription which overflow their bounds. I'm not entirely satisfied with that, since I'm not sure we should have scrollbars at all, especially because they're so ugly on Windows, so I'm going to leave this image open so people have a place to complain about it.

**Comment by gmart7t2** [comment]
I still see scrollbars on some thumbnails even with scrolling=no on the iframe:

![Screenshot_2024-11-04_09-47-31](https://github.com/user-attachments/assets/304274e9-6977-41d3-b182-6f1df8d14090)

**Comment by casey** [comment]
Are those on the iframe element itself, or on an interior element of an HTML inscription? I suppose an HTML inscription could have interior content which overflowed the size it's rendered at. But if that's the case, I'm not sure there's much we can do about it, since we don't want to start monkeying with the contents of HTML inscriptions.

**Comment by casey** [comment]
I wrote up the situation in #4048.
